### PR TITLE
fix: Add option for concatenate action to skip delimiters for null values

### LINKED ISSUE #2430: Add option for concatenate action to skip delimiters for null values

### PR DESCRIPTION
**Pull request by jpav**
Fixes #2430

### CODE REVIEW

File: lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java [hunk 1]
```diff
@@ -72,10 +72,13 @@ public static String concatenate(Concatenate concat, List<String> inputs) {
         }
 
         String delim = concat.getDelimiter() == null ? "" : concat.getDelimiter();
-        StringBuilder builder = new StringBuilder();
+        boolean delimitingEmptyValues = concat.getDelimitingEmptyValues() == null
```
Comment (pleacu) [inline lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java:75]: Isn't this just 
boolean delimitingEmptyValues = !(concat.getDelimitingEmptyValues() == null)

File: ui/packages/atlasmap/src/UI/MappingTransformation.tsx [hunk 2]
```diff
@@ -144,6 +146,16 @@ export const MappingTransformation: FunctionComponent<IMappingTransformationProp
               />
             )}
           </FormGroup>
+        ) : (
```
Comment (pleacu) [inline ui/packages/atlasmap/src/UI/MappingTransformation.tsx:149]: Can you paste a screen shot as to what this looks like.  Also I'm not sure I like `Delimit empty values`.  It's terse which is typically a good thing but maybe too much.  Maybe:
`Add the specified delimiter for empty values.`

**Review by pleacu — COMMENTED** [review]
Adding @igarashitm so he can have a look at the lib side.  He should be resurfacing next week.  I'm concerned about the requirement to version the mapping file.  We've talked about it before - all-in-all probably a good idea - not sure this is the reason for it.

**Comment by igarashitm** [comment]
No need for mapping def version as it's just a minor addition which doesn't break backward compatibility.

File: ui/packages/atlasmap/src/UI/MappingTransformation.tsx (hunk 2 above)
Comment (jpav) [reply ui/packages/atlasmap/src/UI/MappingTransformation.tsx:149]: I don't want to take up too much space for this, as there is already very little real estate to work with or that we are forcing user to expand to.

File: lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java (hunk 1 above)
Comment (jpav) [reply lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java:75]: Not sure if I understand your comment. Based on what you've suggested, if getDelimitingEmptyValues returns False, the variable would end up as true.

Comment (pleacu) [reply lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java:75]: You're right - no ! needed.  Just trying to avoid calling `getDelimitingEmptyValues()` twice.

**Review by pleacu — APPROVED** [review]
+1 - looks ok
