### PR TITLE
fix: UI_REACT: Create namespace view

### LINKED ISSUE #2015: UI_REACT: Create namespace view

### PR DESCRIPTION
**Pull request by jpav**
Fixes #2015

### CODE REVIEW

File: ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx [hunk 1]
```diff
@@ -138,6 +138,17 @@ export const Atlasmap: FunctionComponent<IAtlasmapProps> = ({
...
+        handlers.onCreateNamespace(docName),
+      onEditNamespace: (
+        docName: string,
+        alias: string,
+        uri: string,
+        locationUri: string,
+        isTarget: boolean,
+      ) => handlers.onEditNamespace(docName, alias, uri, locationUri, isTarget),
+      onDeleteNamespace: (docName: string, alias: string) =>
+        handlers.onDeleteNamespace(docName, alias),
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx:151]: No need for this closure, you can pass the function directly

File: ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx [hunk 2]
```diff
@@ -197,6 +224,63 @@ export function useAtlasmapDialogs({
...
 
+  const onCreateNamespace = useCallback(
+    (docName: string) => {
+      title.current = docName;
+      textVal1.current = "";
+      textVal2.current = "";
+      textVal3.current = "";
+      booleanVal.current = false;
+      openCreateNamespaceDialog(
+        (
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx:235]: Same here, just pass the function

File: ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx [hunk 3]
```diff
@@ -197,6 +224,63 @@ export function useAtlasmapDialogs({
...
+      locationUri: string,
+      isTarget: boolean,
+    ) => {
+      title.current = docName;
+      textVal1.current = alias;
+      textVal2.current = uri;
+      textVal3.current = locationUri;
+      booleanVal.current = isTarget;
+      openEditNamespaceDialog(
+        (
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx:263]: Ditto

File: ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx [hunk 4]
```diff
@@ -197,6 +224,63 @@ export function useAtlasmapDialogs({
...
+        ) => {
+          editNamespace(docName, alias, uri, locationUri, isTarget);
+        },
+      );
+    },
+    [editNamespace, openEditNamespaceDialog],
+  );
+
+  const onDeleteNamespace = useCallback(
+    (docName: string, alias: string) => {
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx:278]: Same. Also there is no need to wrap this in useCallback since the function doesn’t change between renders

File: ui-react/packages/atlasmap/src/Atlasmap/utils/ui.ts [hunk 5]
```diff
@@ -95,18 +96,31 @@ export function fromFieldToIFields(field: Field) {
...
+  const namespaces = def.namespaces
+    .map(fromNamespaceModelToINamespace)
+    .filter((n) => n) as IAtlasmapNamespace[];
   return def.visibleInCurrentDocumentSearch && fields.length > 0
     ? {
         id: def.id,
         fields: fields,
         name: def.name,
         type: def.type,
+        namespaces: namespaces,
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Atlasmap/utils/ui.ts:123]: Just `namespaces,`

File: ui-react/packages/atlasmap/src/Views/NamespaceTableView.tsx [hunk 6]
```diff
@@ -0,0 +1,167 @@
...
+import { Actions } from "../UI";
+import { ISourceColumnCallbacks } from "./ColumnMapperView";
+
+const styles = StyleSheet.create({
+  title: { marginTop: "1rem", marginBottom: "1rem" },
+});
+
+export interface INamespaceTableProps {
+  sources: IAtlasmapDocument[];
+  sourceEvents: ISourceColumnCallbacks;
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Views/NamespaceTableView.tsx:36]: I’m not a fan of this. Better have a copy of the interface than coupling the two views together since they are not related

File: ui-react/packages/atlasmap/src/Views/NamespaceTableView.tsx [hunk 7]
```diff
@@ -0,0 +1,167 @@
...
+      <EmptyState variant={EmptyStateVariant.small}>
+        <EmptyStateIcon icon={TableIcon} />
+        <Title headingLevel="h2" size="lg">
+          No sources found
+        </Title>
+      </EmptyState>
+    </Bullseye>
+  ) : (
+    <MainContent>
+      {sources.reduce(
```
Comment (riccardo-forina) [inline ui-react/packages/atlasmap/src/Views/NamespaceTableView.tsx:65]: I’d move this block before the return, it’s pretty complex and difficult to read inside the jsx

File: ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx (hunk 1 above)
Comment (jpav) [reply ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx:151]: Not sure what you're saying here. Do you mean that you'd rather I pass all 3 of these functions directly to the NamespaceTableView via the appropriate handlers.XXX functions, meaning to create separate attributes in that class to receive these?

File: ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx (hunk 2 above)
Comment (jpav) [reply ui-react/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx:235]: Confused what you mean about this one. I get not needing the useCallback, but I don't get "just pass the function". How and to whom?
