### PR TITLE
fix(ui): address UXD feedback

### LINKED ISSUE #2193: Address UXD feedback
Ref [ENTESB-13840](https://issues.redhat.com/browse/ENTESB-13840)

### PR DESCRIPTION
**Pull request by riccardo-forina**
* updated form spacing in the mapping details
* changed columns UI
* toolbars background fixed to white
* expression box made look like a PF control

Fixes #2193

### CODE REVIEW

File: ui/packages/atlasmap/src/UI/Canvas/Arc.tsx [hunk 1]
```diff
@@ -100,7 +80,7 @@ export const Arc: FunctionComponent<IArcProps> = ({
         className={css(props.onClick && styles.clickable)}
         {...props}
       />
-      <ArcEdge
+      {/* <ArcEdge
```
Comment (pleacu) [inline ui/packages/atlasmap/src/UI/Canvas/Arc.tsx:83]: If this is something you'd like to keep then you should create an issue and reference it in the commented out code.  Otherwise we'll forget why we commented it out.

Comment (riccardo-forina) [reply ui/packages/atlasmap/src/UI/Canvas/Arc.tsx]: Thanks, it's save to throw away. I forgot I had it commented.
