### PR TITLE
fix(ui): address UXD feedback for toolbars

### LINKED ISSUE #2122: Toolbars background should be white

### LINKED ISSUE #2123: Reduce the number of icons on the main toolbar

### LINKED ISSUE #2124: Align the conditional expression control to PatternFly guidelines
`f(x)` should be a button control, the text area should be disabled when so, and look like a control when enabled.

### PR DESCRIPTION
**Pull request by riccardo-forina**
Toolbars background is now white, fixes #2122
The main actions (import, export, reset)  are now grouped in a menu,
fixes #2123.
The "Import catalog" doesn't allow for jar files, a new "Import Java archive" voice has been added to do that, fixes ##2110.
Align the conditional expression control to PatternFly guidelines, fixes
 #2124.

### CODE REVIEW

**Comment by riccardo-forina** [comment]
# White toolbars

image

# Grouped main actions, new action to import Java archives

image

# Conditional expression as a control

## Disabled

image

Nor the `f(x)` not the text area are clickable.

## Enabled and with content

image

Happens when a mapping with a mapping expression is selected.
Both the `f(x)` and the text area are clickable. Clicking on `f(x)` will disable the mapping expression for the selected mapping.

## Enabled but without content

image

Happens when a mapping without a mapping expression is selected.
Only the `f(x)` is clickable. Clicking on `f(x)` will enable the mapping expression for the selected mapping.

**Comment by pleacu** [comment]
If I select one of the import icons in the Atlasmap pull-down menu and then I select 'Cancel' from the import dialog then the pull-down menu remains.  Not sure what the PF rules are with regard to a canceled dialog after a menu selection.

**Comment by riccardo-forina** [comment]
I think it should be ok because it's less punitive to the user if he miss-clicked the item than forcing a reopen of the menu. I don't think I have seen any guideline about this, but I might have missed it.

File: ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx [hunk 1]
```diff
@@ -15,17 +24,98 @@ import {
...
+    <ToolbarItem>
+      <Dropdown
+        toggle={
+          <DropdownToggle
+            id="atlasmap-toggle"
+            onToggle={onToggle}
+            iconComponent={CaretDownIcon}
+            data-testid="atlasmap-menu-button"
+          >
+            Atlasmap
```
Comment (igarashitm) [inline ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx:105]: guessing this is the label for the import/export dropdown, AtlasMap (capital M) might be better for user facing label?

Comment (pleacu) [reply ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx:105]: would be cool to have just the new AM logo - just a thought...

Comment (riccardo-forina) [reply ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx]: 🤦‍♂️ every-single-time. Thanks! I need to write a plugin for eslint to catch these...

Comment (riccardo-forina) [reply ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx]: > would be cool to have just the new AM logo - just a thought...

Makes sense, we can try that once ready.
